### PR TITLE
Fix #21: Parameter checking

### LINKED ISSUE #21: Fail if test expects parameters but none provided
At the moment, this test is still executed:

    test('i want lots of values', (t, first, second) => {
        // i am executed
    });

Even though there are no test cases; `first` and `second` will be equal to `undefined`.

We should fail the test immediately if there are more than the `t` parameter without any test cases, or if any of the test cases do not have the right amount of parameters.

### PR DESCRIPTION
**Pull request by Jameskmonger**

### CODE REVIEW

**Comment by Jameskmonger** [comment]
@SiAdcock could you take a look over this when you get a chance? :smile:

File: lib/index.js [hunk 1]
```diff
@@ -15,12 +15,20 @@ var registerTest = function (name, callback, cases) {
...
 
 var registerTestCases = function (name, callback, cases) {
     for (var i = 0; i < cases.length; i++) {
+        if (callback.length - 1 !== cases[i].length) {
+            throw Error('Expected ' + (callback.length - 1) + ' extra arguments for test "' + name + ' [' + i + ']" (found ' + (cases[i].length) + ')');
+        }
+
         var test = new TestCase(name + ' [ ' + cases[i].toString() + ' ]', callback, cases[i]);
         sessionManager.getSession().registerTest(test);
     }
```
Comment (SiAdcock) [inline lib/index.js]: Again I think a `forEach` and a bit of refactoring could make this function more readable

```js
cases.forEach(function(testCase, index) {
  var callbackArgCount = callback.length - 1; 
  var testCaseArgCount = testCase.length;
  
  if (callbackArgCount !== testCaseArgCount) {
    throw Error('Expected ' + callbackArgCount + ' extra arguments for test "' + name + ' [' + index + ']" (found ' + testCaseArgCount + ')');
  }

  var test = new TestCase(name + ' [ ' + testCase.toString() + ' ]', callback, testCase);
  sessionManager.getSession().registerTest(test);
});
```

Comment (Jameskmonger) [inline lib/index.js]: @SiAdcock Will do!
